<?php

    define("REGEX_FILTER_USERNAME", "/[A-Z0-9a-z_-].{6,12}/", true);
    define("REGEX_FILTER_STRATNAME", "/[A-Z0-9a-z_-].{4,20}/", true);
    define("REGEX_FILTER_PASSWORD", "/(?=.*[a-z])(?=.*[A-Z])(?=.*[^\w\d]).{8,16}/", true);
    define("REGEX_FILTER_EMAIL", "/[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])/", true);
    define("END_DIV", "</div>\n", true);
    define("END_SPAN", "</span>\n", true);
    define("END_HEADER", "</header>\n", true);
    define("END_MAIN", "</main>\n", true);
    define("DOESNT_EXIST", "DOESN'T EXIST", true);
    define("END_LABEL", "</label>\n", true);
    define("STRATS_PATH", "../../data/strats/", true);
    define("USERS_PATH", "../../data/users/", true);
    define("TEXT_REDIRECT", "<div id=\"textRedirect\">-- <a href=\"../../index.php\">Index</a> --</div>", true);
    define("LOGOUT_REDIRECT", "<br><div id=\"logoutRedirect\">-- <a href=\"../loginSystem/logout.php\">Login</a> --</div>", true);
    define("SHORT_STRATS_PATH", "../data/strats/", true);
    define("SHORT_USERS_PATH", "../data/users/", true);
    define("IMG_PATH", "../../UI/img/", true);
    define("TEAMS_PATH", "../../data/teams/", true);
    define("USERNAME", "username", true);
    define("PASSWORD", "password", true);
    define("EMAIL", "email", true);
    define("USERNAME_EDIT", "usernameEdit", true);
    define("PASSWORD_EDIT", "passwordEdit", true);
    define("EMAIL_EDIT", "emailEdit", true);
    define("CODE", "code", true);
    define("JSON_EXTENSION", ".json", true);
    define("OLD_VALUE", "oldValue", true);
    define("NEW_VALUE", "newValue", true);
    define("END_FORM", "</form>\n", true);
    define("MAP", "map", true);
    define("MOD", "mod", true);
    define("OBJ", "obj", true);
    define("FILE_NAME", "fileName", true);
    define("FILE_NAME_PERSO", "fileNamePerso", true);
    define("LABEL_USERNAME_LOGIN", "<label class=\"formPreTxt\">Username :</label>\n", true);
    define("LABEL_PASSWORD_LOGIN", "<label class=\"formPreTxt\">Password :</label>\n", true);
    define("LABEL_EMAIL_LOGIN", "<label class=\"formPreTxt\">Email :</label>\n", true);
    define("INPUT_USERNAME_LOGIN", "<input name=\"usernameEdit\" class=\"formEdit\" id=\"usernameEdit\" type=\"text\" placeholder=\"Username\" required />\n", true);
    define("INPUT_PASSWORD_LOGIN", "<input name=\"passwordEdit\" class=\"formEdit\" id=\"passwordEdit\" type=\"password\" placeholder=\"Password\" required /><i id=\"passwordEye\" class=\"fas fa-eye-slash\" onmousedown=\"passwordShow()\" onmouseup=\"passwordHide()\" ></i>\n", true);
    define("INPUT_EMAIL_LOGIN", "<input name=\"email\" class=\"formEdit\" id=\"emailEdit\" type=\"email\" placeholder=\"Email\" required />", true);
    define("INPUT_USERNAME_LOGIN_PATTERN", "<input name=\"usernameEdit\" class=\"formEdit registrationEdit\" id=\"usernameEdit\" type=\"text\" placeholder=\"Username\" pattern=\"".str_replace("/", "", REGEX_FILTER_USERNAME)."\" onchange=\"formChange(this.id)\" required />\n", true);
    define("INPUT_PASSWORD_LOGIN_PATTERN", "<input name=\"passwordEdit\" class=\"formEdit registrationEdit\" id=\"passwordEdit\" type=\"password\" placeholder=\"Password\" pattern=\"".str_replace("/", "", REGEX_FILTER_PASSWORD)."\" onchange=\"formChange(this.id)\" required /><i id=\"passwordEye\" class=\"fas fa-eye-slash\" onmousedown=\"passwordShow()\" onmouseup=\"passwordHide()\" ></i>\n", true);
    define("INPUT_EMAIL_LOGIN_PATTERN", "<input name=\"email\" class=\"formEdit registrationEdit\" id=\"emailEdit\" type=\"email\" placeholder=\"Email\" pattern=\"".str_replace("/", "", REGEX_FILTER_EMAIL)."\" onchange=\"formChange(this.id)\" required />\n", true);
    define("INPUT_FORGOT_PASSWORD_LOGIN", "<a href=\"login.php?mod=2\" ><input name=\"forgotPassword\" class=\"formForgot\" id=\"forgotPassword\" type=\"button\" value=\"Forgot password\" readonly /></a>\n", true);
    define("INPUT_SUBMIT_LOGIN", "<a href=\"login.php?mod=0\" ><input name=\"login\" class=\"formLogin\" id=\"login\" type=\"button\" value=\"Login\" readonly /></a>\n", true);
    define("BOTTOM_BOX", "<div id=\"bottomBox\">\n", true);
    define("TEXT_CODE", "textCode", true);
    define("TEXT_MSG", "textMessage", true);
    define("TEXT_TYPE", "textType", true);
    define("INFO_MSG", "infoMessage", true);
    define("INFO_TYPE", "infoType", true);
    define("CONTACT_TXT_MSG", "Contact | <a href=\"mailto:support@r6stratsmaker.com\">support@r6stratsmaker.com</a>", true);
    define("TEXT_PAGE_LOCATION", "<script type='text/javascript'>document.location.replace('../other/textPage.php');</script>", true);
    define("INDEX_PAGE_LOCATION", "<script type='text/javascript'>document.location.replace('../../index.php');</script>", true);
    define("LOGIN_PAGE_LOCATION", "<script type='text/javascript'>document.location.replace('../loginSystem/login.php');</script>", true);
    define("TEAM_SETTINGS_LOCATION", "<script type='text/javascript'>document.location.replace('teamSettings.php');</script>", true);
    define("INTERNAL_ERROR", "Internal error", true);
    define("JSON_TXT", "jsonTxt", true);
    define("NAME", "name", true);
    define("USER_PROP", "User properties", true);
    define("USER_TYPE", "user_type", true);
    define("JOIN_USERNAME", "joinUsername", true);
    define("TEAM_NAME", "team_name", true);
    define("UBISOFT_LINK", "<a href=\"https://www.ubisoft.com\">Ubisoft</a>", true);
    define("FONT_AWESOME_LINK", "<a href=\"https://www.fontawesome.com\">Font Awesome</a>", true);
    define("CC4_LINK", "<a href=\"https://creativecommons.org/licenses/by/4.0/\">CC BY 4.0 License</a>", true);
    define("FUNKYYSMAPS_LINK", "<a href=\"https://discord.gg/DqRnVVV\">FUNKYYsMAPs</a>", true);
    define("SIL_OFL_1_1_LINK", "<a href=\"https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL\">SIL OFL 1.1 License</a>", true);
    define("MIT_LICENSE_LINK", "<a href=\"https://opensource.org/licenses/MIT\">MIT License</a>", true);
    define("MARCOPIXEL_LINK", "<a href=\"https://marcopixel.eu/r6-operatoricons/\">MarcoPixel</a>", true);
    define("BG_LINK", "../../backgroundsLinks.txt", true);
    define("READONLY", "\" readonly />\n", true);
    define("ERROR", "ERROR", true);
    define("INFO", "INFO", true);
    define("SQL_COMMAND", "sqlCommand", true);
    define("SQL_PARAM", "sqlParam", true);
    define("SQL_ATTR", "sqlAttr", true);

?>


